spring:
  application:
    name: vtradereporter

  datasource:
    url: jdbc:h2:mem:hello
    driver-class-name: org.h2.Driver
    username: sa

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    open-in-view: false
    properties:
      hibernate:
        generate_statistics: false
        jdbc:
          batch_size: 50
          fetch_size: 200
        order_inserts: true
        order_updates: true

  mvc:
    problemdetails:
      enabled: true
