spring:
  application:
    name: vtradereporter

  datasource:
    url: jdbc:h2:mem:hello
    driver-class-name: org.h2.Driver
    username: sa

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    open-in-view: false
